### ISSUE TITLE
code

### ISSUE THREAD

**Issue by kongxinhub** [unmannedlab/LiDARNet#2]
Hi, Peng Jiang. Could you please share the code with me? I want to see some specific details of the code and learn from it. Thank you!

**Comment by maskjp** [comment]
Hi, @kongxin123456 

The code is not ready to release. I made some changes and my coding style is not good. If you really want to read the code, I can send you a version which might be difficult to read. 

Sorry for that. 

Best wishes!

**Comment by kongxinhub** [comment]
> Hi, @kongxin123456
> 
> The code is not ready to release. I made some changes and my coding style is not good. If you really want to read the code, I can send you a version which might be difficult to read.
> 
> Sorry for that.
> 
> Best wishes!

Thank you for your quick reply. I would like to learn the specific settings of the network through the code. In addition, I also want to learn about the processing of multiple data sets. Please send me a copy if it is convenient for you. My email is <kongxin@nuaa.edu.cn>, or you can provide me with a download link.

**Comment by kongxinhub** [comment]
I have one more question. Does the SemanticUSL still have only the sequences 3, 12, 21, and 32 labeled while other sequences are not labeled? If I use SemanticUSL as the source domain data set for training, can I only use the sequence 3,12,21,32? I see that each sequence in the data set has a label folder.

**Comment by maskjp** [comment]
> I have one more question. Does the SemanticUSL still have only the sequences 3, 12, 21, and 32 labeled while other sequences are not labeled? If I use SemanticUSL as the source domain data set for training, can I only use the sequence 3,12,21,32? I see that each sequence in the data set has a label folder.

Yes, only 3,12,21,32 have ground truth. You can use this tool (https://github.com/jbehley/point_labeler) to visualize the data or label your new sequence. You can train a model on the labeled sequences and make predictions for other sequences. And then you can correct the labels using the above tools.

There are some other datasets available  for you to evaluate your own method now, such as 

http://www.cvlibs.net/datasets/kitti-360/

https://www.nuscenes.org/nuscenes

By the way, I send a version of code to you through email. Please check it. 

Hope these information helps!

Best wishes!

**Comment by kongxinhub** [comment]
Sincerely thank you for your help. I have received your email and code, and I will only use the code for personal study and will not share it with others.
