### ISSUE TITLE
SemnaticUSL Validation split 

### ISSUE THREAD

**Issue by gebawe** [unmannedlab/LiDARNet#6]
Hi @maskjp 

Thank you for the interesting work.

I have checked the SemnaticUSL dataset, and it seems that sequence 00 to 08 has some annotation, but they a lot of missing/unlabeled/ignored points. 
i.e., ss = np.fromfile("00/labels/000001.label", dtype=np.int32)
>>> np.unique(ss, return_counts=True)
(array([ 0, 44, 50, 70, 71], dtype=int32), array([125133,    474,   4297,    767,    401]))

![image](https://user-images.githubusercontent.com/30930452/185380412-ffa93f13-f7e9-463d-8263-2c7f00b938bd.png)

Can you please tell me which sequence you have used for validating/Evaluating the model on this SemnaticUSL dataset?

Thank you.

**Comment by maskjp** [comment]
Hi, @awethaileslassie ,

The sequence 3,12,21,32 are fully labeled. We validate on them.

Hope this help!

Best wishes!

**Comment by gebawe** [comment]
Hi @maskjp,

Thank you, that is what I was looking for. 
I suppose including this critical information in the dataset description would help other fellows.
