### ISSUE TITLE
Which field is used for remission ?

### ISSUE THREAD

**Issue by rohithsaro** [unmannedlab/LiDARNet#7]
Dear @maskjp 

Thank you for your impressive work. 
I would like to know which field ( range, intensity, reflectivity ..... ) did you for the dataset and where the values normalized in anyway as i am having trouble with the results after training a network with your dataset. ( Using the same Lidar ).

Also why is the field of view set to 16.6 when the OS1-64 can do 22.5 ?

Eager to hear from you soon.

Regards,
Rohith.

**Comment by maskjp** [comment]
Hi, @rohithsaro,

If I remember correctly, we used intensity.

Sorry, I can't remember clearly. Where did you see the field view is 16.6?

Thanks!
Best wishes!

**Comment by rohithsaro** [comment]
Hi, @maskjp 
Thank you for replying.

Usually the intensity values in OS1-64 range from 0-7000 but In semanticusl.yaml file, it is mentioned the following: 

[proj_remission_mean: 0.20054443
  proj_remission_std: 0.17679570000549158
  **proj_remission_max: 1.0**
  proj_remission_min: 0.0]

Hence why i asked if there was any normalization done for the intensity values. 

As for the field of view, when downloading the zip file containing the datasets, there is a file named OS1-Lidar.yml which has the following:

**v_start_angle: 16.6
v_end_angle: -16.6**
h_start_anlge: 180
h_end_angle: -180
num_beams: 64
num_hsize: 2048
max_range: 80
min_range: 1
front: False
**norm_remission: 1000**

**Comment by maskjp** [comment]
Hi, @rohithsaro,

The ouster we used is the first generation. It only has a field of view between 16.6 to -16.6. I clipped the remission maximum to 1000. I believe. 

https://data.ouster.io/downloads/datasheets/datasheet-gen1-v2p4-os1.pdf

I hope it helps!

Best wishes!

**Comment by rohithsaro** [comment]
Hi, @maskjp 

When you use the term 'clipped', do you mean you excluded all the points above 1000 or re-valued all points above 1000 as 1000 ?

Best regards

**Comment by maskjp** [comment]
@rohithsaro, I think I revalued it to 1000

**Comment by rohithsaro** [comment]
@maskjp 
Thank you, Is there a reason why you had done this ?

**Comment by rohithsaro** [comment]
@maskjp
Thank you, Is there a reason why you had done this ?

Also as mentioned earlier in the semanticusl.yaml file, the remission_max is 1.0, Wouldn't it have to be 1000 ??
